# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Tiffany R. White Blog
tagline:          'Software dev. Pittsburgher. Herder of cats and general contrarian.'
description:      'A Technical Blog by <a href="https://twitter.com/TiffanyW_412" target="_blank">Tiffany White</a>'
url:              'https://tiffanywhite.tech'
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

permalink: /:title/

author:
  name:           'Tiffany White'
  url:            https://twitter.com/TiffanyW_412
  # email:          'tiffany@tiffanywhite.tech'

paginate:         5
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
# disqus:
#   shortname: helloburgh

webmentions:
  username: tiffanywhite.tech
  legacy_domains:
   - http://helloburgh.me
   - https://helloburgh.me
   - https://twhite96.github.io
   - http://twhite96.github.io
  cache_bad_uris_for: 365
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    webmentions: _includes/webmentions/webmentions.html
    reposts: _includes/webmentions/reposts.html
  # debug: true
  # throttle_lookups:
  #   last_week: daily
  #   last_month: weekly
  #   last_year: every 2 weeks
  #   older: monthly

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-cloudinary
  - jekyll-seo-tag
  - octopress-social
  - jekyll-algolia
  - jekyll-font-awesome-sass
  - jekyll-webmention_io
exclude:
  - vendor
# jekyll-archives:
#   enabled:
#     - layout: 'default'
#     - permalinks:
#         year: '/archives/year/:year/'

cloudinary:
  cloud_name: twhiteblog
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

twitter:
  username: TiffanyW_412
  card: summary

# facebook:
#   app_id: 345024175945415
#   admins: 10213908832409124

twitter:
  username:            TiffanyW_412                   # Add your Twitter handle
  tweet_count:         false              # Show number of shares on Twitter
  size:                normal             # Or large
  # embedded_link_color:                    # Set link color for embedded tweets

  follow_count:        true              # Show number of followers
  tweet_message:       ":title by :username :hashtags - :url" # With Tweet button Twitter add the URL last
  tweet_link_text:     Twitter            # Configure the link text
  tweet_link_title:    Share on Twitter   # Share link title
  profile_link_text:   Follow :username
  profile_link_title:  Follow :username on Twitter  # Profile link title text # Profile link title text


# Custom vars
version:            5.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
# search: true
# search_full_content: true # true, false (default)
# search_provider: algolia
# algolia:
#   application_id: VVKLD2O8OY
#   index_name: thatmacnerd
#   search_only_api_key: ce7660039cd338fcfa54fbce856ddd0a
#   powered_by: true

font-awesome:
  assets: true

# pwa:
  # sw_src_filepath: service-worker.js # Optional
  # sw_dest_filename: service-worker.js # Optional
  # dest_js_directory: assets/js # Required
  # precache_recent_posts_num: 5 # Optional
  # precache_glob_directory: / # Optional
  # precache_glob_patterns: # Optional
  #   - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  #   - index.html
  # precache_glob_ignores: # Optional
  #   - sw-register.js
  #   - "fonts/**/*"
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

github:
  repo:             https://github.com/twhite96/
